[package]
name = "nfsserve"
version = "1.0.0"
edition = "2021"
rust-version = "1.96"
authors = ["Rajat Arya <rajat@huggingface.co>", "Assaf Vayner <assaf@huggingface.co>"]
description = "A Rust NFS Server implementation"
homepage = "https://github.com/pr0n00gler/nfsserve"
repository = "https://github.com/pr0n00gler/nfsserve"
readme = "README.md"
keywords = ["nfs"]
license = "BSD-3-Clause"
categories = ["network-programming", "filesystem"]
publish = true
include = ["src/**/*", "src/*", "examples/**/*", "tests/**/*", "benches/**/*", "Cargo.toml", "LICENSE", "README.md"]


[lib]
doctest = false

[dependencies]
byteorder = "1.4"
num-traits = "0.2"
num-derive = "0.4"
tokio = { version = "1", features = ["net", "io-util", "sync", "fs", "rt", "macros", "time"], default-features = false }
tracing = "0.1.31"
anyhow = "1"
async-trait = "0.1.9"
filetime = "0.2"
bytes = "1"
hmac = "0.12"
rand = "0.8"
sha2 = "0.10"
thiserror = "1"

[target.'cfg(windows)'.dependencies]
windows-sys = { version = "0.61", features = ["Win32_Foundation", "Win32_Globalization", "Win32_Storage_FileSystem"] }

# demo
tracing-subscriber = { version = "0.3", features = ["tracing-log"], optional = true }
intaglio = { version = "1.6", optional = true }

[dev-dependencies]
criterion = { version = "0.8.2", default-features = false, features = ["async_tokio", "cargo_bench_support"] }
tracing-subscriber = { version = "0.3", features = ["fmt"] }

[features]
strict = []
demo = ["tracing-subscriber", "tokio/rt-multi-thread", "intaglio"]


[[example]]
name = "demo"
required-features = ["demo"]
path = "examples/demo.rs"

[[example]]
name = "mirrorfs"
required-features = ["demo"]
path = "examples/mirrorfs.rs"

[[example]]
name = "certification_server"
path = "examples/certification_server.rs"

[[bench]]
name = "performance"
harness = false
