name: Native NFSv3 clients

on:
  workflow_dispatch:
  pull_request:
    branches:
      - master
  push:
    branches:
      - main
      - feat/refactoring

jobs:
  same-host:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - if: runner.os == 'Linux'
        run: sudo apt-get update && sudo apt-get install -y nfs-common python3
      - run: ./tests/native/run_local.sh
